language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
before_install:
  - pip install coveralls
install:
  - pip install -e .
  - pip install -r tests/requirements.txt $DJANGO
script: make test
env:
  - DJANGO="Django>=1.11,<1.12"
  - DJANGO="Django>=2.0,<2.1"
  - DJANGO="Django>=2.1,<2.2"
after_success:
  - coveralls
